[tool.poetry]
authors = ["Andreas Andersen <bok.chan@gmail.com>"]
description = ""
name = "github-playground"
packages = [{include = "github_playground"}]
readme = "README.md"
version = "0.0.1"

[tool.poetry.dependencies]
python = "^3.11"

[tool.commitizen]
name = "cz_conventional_commits"
tag_format = "v$version"
version = "0.1.2"
[build-system]
build-backend = "poetry.core.masonry.api"
requires = ["poetry-core"]
